version: '3.8'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - '5173:5173'
        env_file:
            - .env.local
        environment:
            - CHOKIDAR_USEPOLLING=1
